sparkphp/spark

src/Responder/AbstractResponder.php, tests/Responder/AbstractResponderTest.php
Also changed the status code for processing() from 203 to 202, because per the HTTP spec, 202 means "The request has been accepted for processing, but the processing has not been completed."
I would appreciate it if you guys would look at the HTTP status codes I chose for the new methods. I did my best to choose statuses that fit, but there wasn't always a good match.
=> Add methods to AbstractResponder for every Payload status

src/Responder/HtmlResponder.php, src/Responder/JsonResponder.php
The `use` directives at the top of `HtmlResponder` and `JsonResponder` were likely copied from `AbstractResponder` and left in even though they aren't needed.
=> Removed unused use directives from HtmlResponder and JsonResponder

composer.json, src/Application.php
ENV handling should be done at the user level, not forced by the framework.
=> Make dotenv a suggested package instead of a requirement

src/Application.php, src/Handler/ActionHandler.php, src/Resolver/AurynResolver.php, src/Resolver/ResolverInterface.php, tests/ApplicationTest.php, tests/Handler/ActionHandlerTest.php
* `Spark\Resolver\ResolverInterface` is now used for typehinting resolvers
* `Spark\Resolver` is now `Spark\Resolver\AurynResolver`
* `Spark\Resolver\AurynResolver->__invoke()` no longer supports `callable` `$spec` values since that's not a feature we presently use and isn't really tied to the use of Auryn in any way
=> Refactor resolvers to use an interface

src/Application.php, src/Configuration/AurynConfiguration.php, src/Configuration/ConfigurationInterface.php, src/Configuration/ConfigurationSet.php, src/Configuration/DefaultConfigurationSet.php, src/Configuration/DiactorosConfiguration.php, src/Configuration/NegotiationConfiguration.php, src/Configuration/RelayConfiguration.php, tests/ApplicationTest.php, tests/Handler/RouteHandlerTest.php, tests/RouterTest.php
**DO NOT MERGE THIS YET**. It will require a corresponding PR in [sparkphp/project](https://github.com/sparkphp/project) to make corresponding changes to the [application bootstrap file](https://github.com/sparkphp/project/blob/master/web/index.php) to avoid breaking things.
* Add `Configuration` subnamespace with `ConfigurationInterface` for
implementing individual injector configurations
* Remove `Application::boot()` and move its contents into classes
under the `Configuration` subnamespace
* Remove `Application->getInjector()`, `getResolver()`, and
`getRouter()`, as these unnecessarily expose inner workings of the
class
Fixes #35.
=> Add support for injector configurations

.gitattributes
Very minor change, but no reason to litter people's vendor directory.
=> Enable ignoring docs in composer

composer.json, src/Application.php, src/Configuration/RelayConfiguration.php, src/Middleware/Collection.php, src/Middleware/DefaultCollection.php, tests/ApplicationTest.php, tests/Configuration/RelayConfigurationTest.php, tests/Middleware/CollectionTest.php
* Removed the Auryn injector dependency from the `Application` class
* Added a `Middleware` subnamespace with a `Collection` class for
encapsulating the middleware list used by Relay and a
`DefaultCollection` for middlewares used by the Spark core
* Relocated Relay dispatcher configuration to the
`RelayConfiguration` class
* Upgraded Relay to 1.0, which adds a middleware interface usable
for validating references to middleware classes
Fixes #42
=> Modify Application to not use a service locator

src/Formatter/HtmlFormatter.php, src/Responder/FormattedResponder.php, tests/Formatter/HtmlFormatterTest.php, tests/Responder/FormattedResponderTest.php
Per discussion on Hipchat, it makes more sense to not implement `body()` in `HtmlFormatter` and to require subclasses, such as `PlatesFormatter`, to implement it instead.
=> Remove HtmlFormatter->body() implementation

src/Middleware/Collection.php, tests/Middleware/CollectionTest.php
This is intended to be a temporary measure to allow [middlewares included in `Middleware\DefaultCollection`](https://github.com/sparkphp/spark/blob/40ab5f1aded4290b4851e3c22c5ef392363b4e66/src/Middleware/DefaultCollection.php#L17-L22) to be considered valid until such time as they implement `Relay\MiddlewareInterface`.
Refs #50
=> Relax validation in Middleware\Collection

src/Configuration/DefaultConfigurationSet.php, src/Configuration/PayloadConfiguration.php
This configures the injector to use Spark's `Payload` implementation of `PayloadInterface` so that Spark users don't have to in order to type hint against `PayloadInterface` in domain classes.
=> Add PayloadConfiguration to DefaultConfigurationSet

src/Configuration/DiactorosConfiguration.php, tests/Configuration/DiactorosConfigurationTest.php
Allows type hinting against either `ServerRequestInterface` or
`RequestInterface` without creating separate instances for both.
=> Alias request to server request

docs/index.md
Forgot that `FormatterResponder` is immutable, so the example that tries to modify it to integrate Plates needs to use delegation, not preparation.
=> Correct a docs issue regarding Plates integration

docs/index.md, src/Configuration/DefaultConfigurationSet.php, src/Configuration/PlatesResponderConfiguration.php, tests/Configuration/ConfigurationTestCase.php, tests/Configuration/DiactorosConfigurationTest.php, tests/Configuration/PlatesResponderConfigurationTest.php, tests/Configuration/RelayConfigurationTest.php
Allows Plates to be used easily without having to implement a custom
configuration.
Also allows easier extension of the `DefaultConfigurationSet` by
including the `$classes` parameter, which is merged with the defaults.
Simplifies the configuration tests by defining a base test case that
automatically creates the injector and applies all required configs.
=> Add plates responder configuration

src/Responder/FormattedResponder.php, tests/Responder/FormattedResponderTest.php
By eliminating attempts to run formatting on blank output, it becomes
easier to use redirection in combination with other responses.
=> Stop using response formatter with empty output

docs/index.md, src/Middleware/Collection.php, tests/Middleware/CollectionTest.php
Often it is necessary to add middleware to an existing set and
sometimes it needs to be placed specifically. Creating a whole new
collection is often tedious and can be easily abstracted.
Fixes #79
=> Allow middleware to be added to collections

composer.json, src/Input.php, src/Router.php, tests/Fake/FakeInput.php, tests/Handler/ActionHandlerTest.php, tests/InputTest.php, tests/Router/RouteTest.php, tests/RouterTest.php
Since this is the only package that makes use of the Input class,
it should be the one to hold it. The ADR package should only contain
interfaces and not concrete classes.
Also adds unit tests for the input class.
Refs sparkphp/adr#7
=> Merge input class from adr package

composer.json, src/Configuration/ConfigurationSet.php, src/Middleware/Collection.php, src/Middleware/DefaultCollection.php, tests/Configuration/ConfigurationSetTest.php, tests/Configuration/DefaultConfigurationSetTest.php, tests/Configuration/RelayConfigurationTest.php, tests/Middleware/CollectionTest.php
Enables a standard, immutable interface to be used for both config and
middleware sets. Also ensures that config and middleware is never
duplicated.
=> Use Destrukt for config and middleware sets

src/Configuration/DiactorosConfiguration.php, tests/Configuration/DiactorosConfigurationTest.php
Sharing requests and responses does not work, because the objects are
immutable and the shared instance would almost never be the instance
that would be used by a method.
Also adds missing alias for `RequestInterface`.
=> Correct aliases for diactoros

src/Responder/ChainedResponder.php, src/Responder/RedirectResponder.php, tests/Responder/RedirectResponderTest.php
Often an application will need to redirect the user from one location
to another. This makes it easy to do so by using Payload variables:
- `redirect` sets the URI to redirect to
- `status` optionally sets the HTTP code to use
Refs wheniwork/widgets#20
=> Add a redirect responder

tests/Configuration/PlatesResponderConfigurationTest.php, tests/Formatter/PlatesFormatterTest.php
Prevents complete failures when Plates is not installed. This can
happen when using global phpunit with a non-dev install.
=> Skip plates tests when not available

src/Configuration/AurynConfiguration.php, tests/Configuration/AurynConfigurationTest.php
Instead of having a single Auryn instance, explicitly set the resolver
parameter to the configured instance. This allows for separate
application instances. One possible use case is to have composite
responses as some sort of "batch" endpoint.
=> Remove injector singleton

composer.json, docs/index.md, src/Configuration/WhoopsConfiguration.php, src/Handler/ExceptionHandler.php, src/Handler/ExceptionHandlerPreferences.php, tests/Handler/ExceptionHandlerPreferencesTest.php, tests/Handler/ExceptionHandlerTest.php
Having a content negotiated exception handler provides more robust
debugging capabilities in multiple contexts. [Whoops][1] has the added
benefit of being capable of logging.
By having a separate class for the preferred handlers the user can
customize which handlers will be used easily.
[1]: https://github.com/filp/whoops
Fixes #89
=> Replace custom exception handler with whoops

docs/index.md, src/Configuration/ConfigurationSet.php, tests/Configuration/ConfigurationSetTest.php
Sometimes it is more convenient to pass a fully constructed object than
to use a specification only. For example, when using `EnvConfiguration`
a user might want to define the file path directly in the boostrap.
Refs #101
=> Allow objects to be in used in configuration sets

src/Configuration/EnvConfiguration.php, tests/Configuration/EnvConfigurationTest.php
The `&&` operator has a higher precedence than the `=` operator, so $dir was actually getting set to 1.
=> Fix bugs in detectEnvFile()

src/Handler/ActionHandler.php, src/Handler/DispatchHandler.php, tests/Fake/FakeDomain.php, tests/Handler/ActionHandlerTest.php, tests/Handler/DispatchHandlerTest.php
The action handler was not actually using any of the Arbiter methods,
except for the resolver. Stop extending it and clean methods and docs.
Also reduces repetition by using a constant for the action attribute
that is shared between the action and dispatch handlers.
=> Clean up action and dispatch handler

src/Input.php, tests/InputTest.php
According to [PSR-7 spec][1] the parsed body of a request may return an
object or array or null. Handle all of these cases properly.
Also improves how the input array is generated by using a single
`array_replace` call.
[1]: http://www.php-fig.org/psr/psr-7/#3-2-1-psr-http-message-serverrequestinterface
=> Improve input handling of parsed bodies

src/Handler/ContentHandler.php, src/Handler/FormContentHandler.php, src/Handler/JsonContentHandler.php, tests/Handler/ContentHandlerTestCase.php
Some simple changes to improve the content handler style and function:
- remove yoda conditions
- allow any `application/*json` content type
- remove interface aliases
- normalize whitespace
=> Clean up content handlers

composer.json, docs/index.md, src/Configuration/PlatesResponderConfiguration.php, src/Resolver/ResolverTrait.php, src/Responder/ChainedResponder.php, src/Responder/FormattedResponder.php, tests/Configuration/PlatesResponderConfigurationTest.php, tests/Responder/ChainedResponderTest.php, tests/Responder/FormattedResponderTest.php
By converting these responders into a set and a dictionary validation
is automatically handled and modification becomes easier.
Also adds a `ResolverTrait` to DRY usage of the resolver.
=> Make chained and formatted responders into sets
