.travis.yml, README.md, composer.json, phpunit.php, phpunit.xml.dist, tests/ApplicationTest.php, tests/Fake/FakeActionHandler.php, tests/Fake/FakeDomain.php, tests/Fake/FakeExceptionHandler.php, tests/Fake/FakeInput.php, tests/Fake/FakeResponder.php, tests/Responder/ResponderTest.php, tests/Router/RouteTest.php, tests/RouterTest.php
@shadowhand @ameech Feel free to add more tests. In no way is this complete.
=> All the tests!

.travis.yml, src/Application.php
josegonzalez\Dotenv was already in composer.json, but was never actually being used.
=> Load .env file in Application::boot

phpunit.php, src/Handler/ExceptionHandler.php
Application root can be guessed or manually set instead.
Fixes #16
=> Remove the APP_PATH constant

composer.json, src/Responder/PlatesResponder.php
Also suggest `league/plates` with Composer.
cc @elazar
=> Add PlatesResponder for templated HTML

composer.json, src/Handler/ActionHandler.php, src/Payload.php, src/Responder/AbstractResponder.php, src/Responder/HtmlResponder.php, src/Responder/JsonResponder.php, src/Responder/PlatesResponder.php, tests/Fake/FakeDomain.php, tests/Responder/AbstractResponderTest.php, tests/Responder/HtmlResponderTest.php, tests/Responder/JsonResponderTest.php
@shadowhand @elazar @ameech 
This is just the initial Payload. I'm wondering how we should handle setting HTTP status codes and other response information given the change in the Payload.
=> Change Payload

.codeclimate.yml
Exclude the test directories from the analysis.
=> Add code climate config

src/Handler/ContentHandler.php, tests/Handler/ContentHandlerTest.php
Enable parsing of JSON and form input to be used for input.
=> Add ContentHandler for parsing request body

docs/index.md, mkdocs.yml
Let me know what you guys think.
Using http://docs.readthedocs.org/en/latest/getting_started.html#in-markdown
=> Documentation

.travis.yml
No reason to allow it to fail.
=> Remove allowing HHVM failures

src/Handler/FormContentHandler.php, src/Middleware/DefaultCollection.php
Defaults to using JSON content handler.
=> Add concrete content handler

src/Middleware/Collection.php, tests/Middleware/CollectionTest.php
=> Fix validation check in MiddlewareCollection

src/Configuration/DiactorosConfiguration.php
These values should be singleton, at least for now.
=> Share request and response globally

src/Configuration/ConfigurationSet.php
Enables the user to add custom config to the default set.
Refs #60
=> Modify configuration set to allow additions

docs/index.md
Received an e-mail from a random Spark user this morning:
```
from: Zsolt Sándor <ezsolt@gmail.com>
to: me@matthewturland.com
date: Wed, Nov 18, 2015 at 8:59 AM
subject: sparkphp -- plates -- example
Hi Elazar
I just wanted to ask if you could provide an usage example for plates and spark 0.7?
I can't figure it out how to use it.
Thanks
Zsolt Sándor
gtaphic designer
70 257 5720
www.be.net/zsolt
```
I noticed he's right, the docs are a bit light on responder customization, so I added to them to cover his use case.
Also noticed and fixed a copy-paste error in the process. See if you can spot it. The irony of it is not lost on me.
=> Responder customization examples

docs/index.md
=> Update Plates integration example to be more concise

docs/data.md
=> Move sparkphp/data documentation to this repo

docs/auth.md
=> Add documentation for auth body extractor

composer.json, src/Configuration/ConfigurationSet.php, src/Middleware/Collection.php
Package has moved to an organization.
Refs #84
=> Switch destrukt dependency

docs/index.md
A number of minor fixes:
- remove unnecessary slashes
- use `Acme` namespace universally instead of `My`
- fix middleware value adding references
Refs #95
=> Clean up spark docs

docs/index.md
=> Add documentation for redirect responder

composer.json, docs/index.md, src/Configuration/EnvConfiguration.php, src/Env.php, src/Exception/EnvException.php, tests/Configuration/ConfigurationTestCase.php, tests/Configuration/EnvConfigurationTest.php
Often projects will need some kind of configuration for the application
environment. The current best practice is to store configuration in an
ini file that is parsed.
=> Add env configuration support

docs/session.md, mkdocs.yml
https://github.com/sparkphp/session
=> Add documentation for the session library

src/Application.php, tests/ApplicationTest.php
=> Apply configuration directly with set

src/Formatter/AbstractFormatter.php, src/Formatter/HtmlFormatter.php, src/Formatter/JsonFormatter.php, src/Formatter/PlatesFormatter.php
Normalize whitespace and method precedence in formatters.
=> Clean up formatters

docs/index.md
Documentation got a bit out of sync with recent changes and referenced
things that were no longer correct.
=> Correct documentation around responders and formatters
